name: prova1
version: '0.1'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary

description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  prova1:
    # See 'snapcraft plugins'
    plugin: make
    source: .
    stage-packages:
      - xauth
      - libappindicator3-1
      - gnome-icon-theme
    build-packages:
      - intltool
      - libappindicator3-dev
      - libavahi-ui-gtk3-dev
      - libgcrypt20-dev
      - libgnome-keyring-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsoup2.4-dev
      - libspice-client-gtk-3.0-dev
      - libspice-protocol-dev
      - libvncserver-dev
      - libvte-2.91-dev
      - libxkbfile-dev
    organize:
      snap/prova1/current: .

  desktop-gtk3:
    stage:
      - -./usr/share/fonts/**
    install: |
      set -x
      export XDG_DATA_DIRS=$SNAPCRAFT_PART_INSTALL/usr/share
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done


apps:
  prova1:
    command: desktop-launch prova1
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - pulseaudio
      - unity7
      - password-manager-service
      - wayland

slots:
  prova1-gapp:
    interface: dbus
    bus: session
    name: org.gtk.example


    
